<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>RuoYi.Common.Web</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RuoYi.Common.Core\RuoYi.Common.Core.csproj" />
    <ProjectReference Include="..\RuoYi.Common.Security\RuoYi.Common.Security.csproj" />
  </ItemGroup>
</Project>